version: "3"

services:
  voteapp:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - frontend
      - backend

  resultapp:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - frontend
      - backend

  workerservice:
    build:
      context: ./worker
    depends_on:
      - "rediscache"
      - "maindb"
    networks:
      - backend

  rediscache:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - backend

  maindb:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "maindb-data:/var/lib/postgresql/data"
    networks:
      - backend

volumes:
  maindb-data:

networks:
  frontend:
  backend: