apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maindb
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maindb
  template:
    metadata:
      labels:
        app: maindb
    spec:
      volumes:
      - name: maindb-data
        emptyDir: {}
      containers:
      - image: postgres:9.4
        name: db
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: maindb-data
       