apiVersion: v1
kind: Service
metadata:
  labels:
    app: resultapp
  name: resultapp
spec:
  type: NodePort
  ports:
  - name: "resultapp-service"
    port: 5001
    targetPort: 80
    nodePort: 32001
  selector:
    app: resultapp