apiVersion: v1
kind: Service
metadata:
  labels:
    app: voteapp
  name: voteapp
spec:
  type: NodePort
  ports:
  - name: "voteapp-service"
    port: 5000
    targetPort: 80
    nodePort: 32000
  selector:
    app: voteapp
  